locale: "en-US"
title: "Tales of a Developer"
title_separator: "|"
name: "Miguel Sánchez Villafán"
description: "A blog about mig8447's day to day learning in the world of software development"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mig8447.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: "mig8447/mig8447.github.io"
comments:
    provider: "disqus"
    disqus:
        shortname: "mig8447"
author:
    name: "Miguel Sánchez Villafán"
    bio: "Full-time software developer and development manager for Oracle, ocassionally a photographer, and definitely a music lover"
    avatar: "/assets/images/avatar.jpg"
    location: "Guadalajara, Jalisco, México"
    flickr: mig8447
    github: mig8447
    linkedin: mig8447
paginate: 10
timezone: America/Mexico_City
category_archive:
    type: liquid
    path: /categories/
tag_archive:
    type: liquid
    path: /tags/
search: true
og_image: /assets/images/avatar.jpg

defaults:
    # _posts
    - scope:
        path: ""
        type: posts
      values:
        layout: single
        read_time: true
        comments: true
        share: true
        related: true
        author_profile: true

# Build settings
markdown: kramdown
#remote_theme: "fongandrew/hydeout"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"
plugins:
    - jekyll-feed
    - jekyll-gist
    - jekyll-paginate
    - jekyll-sitemap
    - jemoji

